export const INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE';
export const INSUFFICIENT_STOCKS = 'INSUFFICIENT_STOCKS';
export const DUPLICATED_OPERATION = 'DUPLICATED_OPERATION';
export const MARKET_CLOSED = 'MARKET_CLOSED';
export const INVALID_OPERATION = 'INVALID_OPERATION';
